# Generated by Django 4.0.5 on 2022-07-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='good_details',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionform',
            name='service_details',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
