# Generated by Django 4.0.5 on 2022-07-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0002_alter_requisitionform_good_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localpurchaseorder',
            name='datetime',
        ),
    ]
