# Generated by Django 4.0.5 on 2022-07-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0004_quote_quote_file_name_alter_quote_quote_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_file_name', models.CharField(default='', max_length=65)),
                ('quote_file', models.FileField(upload_to='quotes/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_file_name',
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requisition.quotefile'),
        ),
    ]
