# Generated by Django 4.0.5 on 2022-07-21 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisition', '0009_remove_quote_created_at_remove_quote_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_file_name',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AddField(
            model_name='quote',
            name='requisition',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='requisition.requisitionform'),
        ),
        migrations.AddField(
            model_name='quote',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
    ]
