# Generated by Django 4.0.5 on 2022-07-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0010_quote_created_at_quote_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_file',
        ),
    ]
