# Generated by Django 4.0.5 on 2022-07-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0011_remove_quote_quote_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_file', models.FileField(default='', upload_to='quotes/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quote_file_name',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='requisition.quotefile'),
        ),
    ]
