# Generated by Django 4.0.5 on 2022-07-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0012_quotefile_remove_quote_quote_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionform',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='requisitionform',
            name='status',
            field=models.CharField(choices=[('Approved', 'APPROVED'), ('Rejected', 'REJECTED'), ('Pending', 'PENDING')], default='Pending', max_length=35),
        ),
    ]
