# Generated by Django 4.0.5 on 2022-07-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0013_requisitionform_reason_requisitionform_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionform',
            old_name='good_details',
            new_name='good_description',
        ),
        migrations.RenameField(
            model_name='requisitionform',
            old_name='service_details',
            new_name='service_description',
        ),
    ]
