# Generated by Django 4.0.5 on 2022-07-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0014_rename_good_details_requisitionform_good_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionform',
            name='good',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='requisitionform',
            name='service',
            field=models.CharField(default='', max_length=60),
        ),
    ]
