# Generated by Django 4.0.5 on 2022-07-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0015_requisitionform_good_requisitionform_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisitionform',
            old_name='good',
            new_name='goods',
        ),
    ]
