# Generated by Django 4.0.5 on 2022-07-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0017_rename_good_description_requisitionform_goods_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionform',
            name='requisition_type',
            field=models.CharField(choices=[('SGS', 'SINGLE SOURCE'), ('NML', 'NORMAL')], max_length=35),
        ),
    ]
