# Generated by Django 4.0.5 on 2022-07-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0018_alter_requisitionform_requisition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionform',
            name='req_condition',
            field=models.CharField(choices=[('Budgeted', 'BUDGETED'), ('Emergency', 'EMERGENCY'), ('Unplanned', 'UNPLANNED')], default='', max_length=35),
        ),
    ]
