# Generated by Django 4.0.5 on 2022-07-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0020_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpurchaseorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
