# Generated by Django 4.0.5 on 2022-07-31 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requisition', '0022_alter_localpurchaseorder_delivery_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpurchaseorder',
            name='order_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firstName', to=settings.AUTH_USER_MODEL),
        ),
    ]
