# Generated by Django 4.0.5 on 2022-08-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0023_alter_localpurchaseorder_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpurchaseorder',
            name='description_of_goods',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='localpurchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='localpurchaseorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
