# Generated by Django 4.0.5 on 2022-08-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0024_alter_localpurchaseorder_description_of_goods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_file',
        ),
        migrations.AddField(
            model_name='quotefile',
            name='quote',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='requisition.quote'),
        ),
    ]
