# Generated by Django 4.0.5 on 2022-08-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0028_remove_quote_supplier_quotefile_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='status',
        ),
        migrations.AddField(
            model_name='quotefile',
            name='status',
            field=models.CharField(choices=[('Approved', 'APPROVED'), ('Rejected', 'REJECTED'), ('Pending', 'PENDING')], default='Pending', max_length=35),
        ),
    ]
