# Generated by Django 4.0.5 on 2022-08-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0029_remove_quote_status_quotefile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpurchaseorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localpurchaseorder',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
