# Generated by Django 4.0.5 on 2022-08-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0030_localpurchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionform',
            name='item_name',
            field=models.CharField(default='', max_length=65),
        ),
    ]
