# Generated by Django 4.0.5 on 2022-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0031_requisitionform_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionform',
            name='category',
            field=models.CharField(choices=[('Electronics', 'ELECTRONICS'), ('Cutlery', 'CUTLERY'), ('Stationery', 'STATIONERY')], default='', max_length=35),
        ),
    ]
