# Generated by Django 4.0.5 on 2022-08-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0033_alter_requisitionform_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotefile',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='quotefile',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='requisitionform',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='requisitionform',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
