# Generated by Django 4.0.5 on 2022-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0034_quotefile_deleted_quotefile_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpurchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
