# Generated by Django 4.0.5 on 2022-07-14 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('GDS', 'GOODS'), ('SVR', 'SERVICE')], max_length=35)),
                ('good_details', models.CharField(blank=True, default='', max_length=650)),
                ('service_details', models.CharField(blank=True, default='', max_length=650)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=12)),
                ('type_of_purchase', models.CharField(choices=[('SGS', 'SINGLE SOURCE'), ('NML', 'NORMAL')], max_length=35)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quarter_year', models.CharField(choices=[('Q1', 'Quarter 1'), ('Q2', 'Quarter 2'), ('Q3', 'Quarter 3'), ('Q4', 'Quarter 4')], default='', max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='supplier.supplier')),
            ],
        ),
    ]
