# Generated by Django 4.0.5 on 2022-07-14 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annual_procurement_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementplan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procurementplan',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
    ]
