# Generated by Django 4.0.5 on 2022-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_procurement_plan', '0005_procurementplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementplan',
            name='category',
            field=models.CharField(choices=[('Electronics', 'ELECTRONICS'), ('Cutlery', 'CUTLERY'), ('Stationery', 'STATIONERY')], default='', max_length=35),
        ),
    ]
