# Generated by Django 4.0.5 on 2022-08-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_procurement_plan', '0007_alter_procurementplan_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementplan',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='procurementplan',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
