# Generated by Django 4.0.5 on 2022-08-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_procurement_plan', '0008_procurementplan_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementplan',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='procurementplan',
            name='deleted_by_cascade',
        ),
    ]
