# Generated by Django 4.0.5 on 2022-07-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_is_ceo_user_is_head_of_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_head_of_department',
        ),
    ]
