# Generated by Django 4.0.5 on 2022-07-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_remove_department_created_by_and_more'),
        ('authentication', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_head_department',
            field=models.BooleanField(default=False),
        ),
    ]
