# Generated by Django 4.0.5 on 2022-07-15 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annual_procurement_plan', '0003_alter_procurementplan_created_by'),
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPlanApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procurement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annual_procurement_plan.procurementplan')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvals.status')),
            ],
        ),
    ]
