# Generated by Django 4.0.5 on 2022-07-15 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_procurementplanapprovals'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='procurementplanapprovals',
            table='Procurement plan approvals',
        ),
    ]
