# Generated by Django 4.0.5 on 2022-07-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0006_alter_approvee_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvee',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
