# Generated by Django 4.0.5 on 2022-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0010_alter_approvee_approval_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteapprovals',
            name='status',
        ),
        migrations.AlterField(
            model_name='procurementplanapprovals',
            name='status',
            field=models.CharField(choices=[('Approved', 'APPROVED'), ('Rejected', 'REJECTED'), ('Pending', 'PENDING')], default='Pending', max_length=35),
        ),
        migrations.AlterField(
            model_name='requisitionformapprovals',
            name='status',
            field=models.CharField(choices=[('Approved', 'APPROVED'), ('Rejected', 'REJECTED'), ('Pending', 'PENDING')], default='Pending', max_length=35),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
