# Generated by Django 4.0.5 on 2022-07-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0020_quote_status'),
        ('approvals', '0012_rename_created_at_quoteapprovals_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteApprovee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QuoteApprovals',
        ),
        migrations.RenameField(
            model_name='approvee',
            old_name='approvee_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='approvee',
            name='procurement_plan',
        ),
        migrations.RemoveField(
            model_name='approvee',
            name='requisition',
        ),
        migrations.AddField(
            model_name='quoteapprovee',
            name='approvee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.approvee'),
        ),
        migrations.AddField(
            model_name='quoteapprovee',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.quote'),
        ),
    ]
