# Generated by Django 4.0.5 on 2022-07-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annual_procurement_plan', '0004_procurementplan_description'),
        ('approvals', '0013_quoteapprovee_delete_quoteapprovals_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPlanApprovee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approvee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.approvee')),
                ('procurement_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annual_procurement_plan.procurementplan')),
            ],
        ),
        migrations.DeleteModel(
            name='ProcurementPlanApprovals',
        ),
    ]
