# Generated by Django 4.0.5 on 2022-07-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0020_quote_status'),
        ('approvals', '0014_procurementplanapprovee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionFormApprovee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approvee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approvals.approvee')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.requisitionform')),
            ],
        ),
        migrations.DeleteModel(
            name='RequisitionFormApprovals',
        ),
    ]
