# Generated by Django 4.0.5 on 2022-07-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
    ]
