# Generated by Django 4.0.5 on 2022-08-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_remove_department_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
